// Generated by tools/capture-fulltext.mjs from MySQL 8.4.11; do not edit.
//
// InnoDB's default stopwords (INFORMATION_SCHEMA.INNODB_FT_DEFAULT_STOPWORD)
// and its token bounds (@@innodb_ft_min_token_size, @@innodb_ft_max_token_size).

export const FT_STOPWORDS: ReadonlySet<string> = new Set(['a', 'about', 'an', 'are', 'as', 'at', 'be', 'by', 'com', 'de', 'en', 'for', 'from', 'how', 'i', 'in', 'is', 'it', 'la', 'of', 'on', 'or', 'that', 'the', 'this', 'to', 'und', 'was', 'what', 'when', 'where', 'who', 'will', 'with', 'www'])
export const FT_MIN_TOKEN = 3
export const FT_MAX_TOKEN = 84
