// The diagnostics area (M5.28), as 8.4.11 answered each of these statements
// in its default sql_mode.
//
// SHOW WARNINGS lists the last statement's conditions, notes included, and
// SHOW ERRORS its errors. Neither clears them, and nor do their COUNT(*)
// forms. Every other statement starts afresh, after `@@warning_count` has
// been read. An error is a condition too. The conditions come from storing
// values, IGNORE, DDL deprecations and duplicate keys, IF [NOT] EXISTS notes
// and SET. Outside a strict mode, data too long is 1265, and so is a temporal
// that does not parse; one that parses but is impossible is 1264. Expressions
// warn too: text read as a number (1292 DOUBLE, INTEGER or DECIMAL),
// division by zero (1365), CAST's truncations and clamps (1292, 1264, 1105),
// a string past max_allowed_packet (1301), and a sort over JSON arrays or
// objects (1235, once a statement). A constant compared with a number is
// converted once a statement; anything else, each time it is read.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import mysql from 'mysql2/promise'
import { MySQL } from '@myjs/core'

type Outcome = readonly (readonly (string | null)[])[] | readonly [number, number, string, number] | readonly [number, string]

const SCRIPT: readonly (readonly [string, Outcome])[] = [
  ["CREATE TABLE t (a TINYINT, b VARCHAR(3))", [0,0,"",0]],
  ["INSERT IGNORE INTO t VALUES (300, 'abcdef'), (-300, 'x')", [2,0,"Records: 2  Duplicates: 0  Warnings: 3",3]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'a' at row 1"],["Warning","1265","Data truncated for column 'b' at row 1"],["Warning","1264","Out of range value for column 'a' at row 2"]]],
  ["SHOW COUNT(*) WARNINGS", [["3"]]],
  ["SELECT @@warning_count, @@error_count", [["3","0"]]],
  ["SHOW WARNINGS", []],
  ["INSERT IGNORE INTO t VALUES (300, 'abcdef'), (-300, 'x')", [2,0,"Records: 2  Duplicates: 0  Warnings: 3",3]],
  ["SHOW WARNINGS LIMIT 1", [["Warning","1264","Out of range value for column 'a' at row 1"]]],
  ["SHOW WARNINGS LIMIT 1, 1", [["Warning","1265","Data truncated for column 'b' at row 1"]]],
  ["SHOW ERRORS", []],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'a' at row 1"],["Warning","1265","Data truncated for column 'b' at row 1"],["Warning","1264","Out of range value for column 'a' at row 2"]]],
  ["SELECT * FROM nope", [1146,"Table 'app.nope' doesn't exist"]],
  ["SHOW WARNINGS", [["Error","1146","Table 'app.nope' doesn't exist"]]],
  ["SHOW ERRORS", [["Error","1146","Table 'app.nope' doesn't exist"]]],
  ["SHOW COUNT(*) ERRORS", [["1"]]],
  ["SELECT @@error_count", [["1"]]],
  ["SHOW WARNINGS", []],
  ["CREATE TABLE t2 (d DECIMAL(4,1), dt DATE, v VARCHAR(2), f FLOAT(3,1), n INT NOT NULL, e ENUM('a'))", [0,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1681","Specifying number of digits for floating point data types is deprecated and will be removed in a future release."]]],
  ["INSERT INTO t2 (d, dt, v, f, n) VALUES (1.25, '2020-01-01 10:00:00', 'a   ', 1.25, 1)", [1,0,"",3]],
  ["SHOW WARNINGS", [["Note","1265","Data truncated for column 'd' at row 1"],["Note","1292","Incorrect date value: '2020-01-01 10:00:00' for column 'dt' at row 1"],["Note","1265","Data truncated for column 'v' at row 1"]]],
  ["SET sql_mode = ''", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["INSERT INTO t2 (d, dt, v, f, n) VALUES (1.25, '2020-01-01 10:00:00', 'a   ', 1.25, 1)", [1,0,"",3]],
  ["SHOW WARNINGS", [["Note","1265","Data truncated for column 'd' at row 1"],["Note","1265","Data truncated for column 'dt' at row 1"],["Note","1265","Data truncated for column 'v' at row 1"]]],
  ["INSERT INTO t2 (d) VALUES (1)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1364","Field 'n' doesn't have a default value"]]],
  ["INSERT INTO t2 (n, dt) VALUES (1, 'junk')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'dt' at row 1"]]],
  ["UPDATE t2 SET n = NULL", [4,0,"Rows matched: 4  Changed: 3  Warnings: 4",4]],
  ["SHOW WARNINGS", [["Warning","1048","Column 'n' cannot be null"],["Warning","1048","Column 'n' cannot be null"],["Warning","1048","Column 'n' cannot be null"],["Warning","1048","Column 'n' cannot be null"]]],
  ["SET sql_mode = 'STRICT_TRANS_TABLES'", [0,0,"",1]],
  ["SHOW WARNINGS", [["Warning","3135","'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release."]]],
  ["SET sql_mode = DEFAULT", [0,0,"",0]],
  ["CREATE TABLE t3 (a TINYINT(1) ZEROFILL, b FLOAT(3,1) UNSIGNED, KEY (a), KEY (a))", [0,0,"",5]],
  ["SHOW WARNINGS", [["Warning","1681","The ZEROFILL attribute is deprecated and will be removed in a future release. Use the LPAD function to zero-pad numbers, or store the formatted numbers in a CHAR column."],["Warning","1681","Integer display width is deprecated and will be removed in a future release."],["Warning","1681","Specifying number of digits for floating point data types is deprecated and will be removed in a future release."],["Warning","1681","UNSIGNED for decimal and floating point data types is deprecated and support for it will be removed in a future release."],["Warning","1831","Duplicate index 'a_2' defined on the table 'app.t3'. This is deprecated and will be disallowed in a future release."]]],
  ["DROP TABLE IF EXISTS nope, nope2", [0,0,"",2]],
  ["SHOW WARNINGS", [["Note","1051","Unknown table 'app.nope'"],["Note","1051","Unknown table 'app.nope2'"]]],
  ["DROP VIEW IF EXISTS nv", [0,0,"",1]],
  ["SHOW WARNINGS", [["Note","1051","Unknown table 'app.nv'"]]],
  ["CREATE TABLE IF NOT EXISTS t3 (a INT)", [0,0,"",1]],
  ["SHOW WARNINGS", [["Note","1050","Table 't3' already exists"]]],
  ["CREATE DATABASE IF NOT EXISTS rvx_db", [1,0,"",0]],
  ["CREATE DATABASE IF NOT EXISTS rvx_db", [1,0,"",1]],
  ["SHOW WARNINGS", [["Note","1007","Can't create database 'rvx_db'; database exists"]]],
  ["DROP DATABASE rvx_db", [0,0,"",0]],
  ["DROP DATABASE IF EXISTS nodb_rv", [0,0,"",1]],
  ["SHOW WARNINGS", [["Note","1008","Can't drop database 'nodb_rv'; database doesn't exist"]]],
  ["CREATE TABLE ft (a TEXT, b INT)", [0,0,"",0]],
  ["ALTER TABLE ft ADD FULLTEXT (a)", [0,0,"Records: 0  Duplicates: 0  Warnings: 1",1]],
  ["SHOW WARNINGS", [["Warning","124","InnoDB rebuilding table to add column FTS_DOC_ID"]]],
  ["ALTER TABLE ft ADD INDEX (b), ADD INDEX (b)", [0,0,"Records: 0  Duplicates: 0  Warnings: 1",1]],
  ["SHOW WARNINGS", [["Warning","1831","Duplicate index 'b_2' defined on the table 'app.ft'. This is deprecated and will be disallowed in a future release."]]],
  ["ALTER TABLE ft ADD COLUMN c FLOAT(3,1) UNSIGNED, ADD COLUMN d INT(4) ZEROFILL", [0,0,"Records: 0  Duplicates: 0  Warnings: 4",4]],
  ["SHOW WARNINGS", [["Warning","1681","Specifying number of digits for floating point data types is deprecated and will be removed in a future release."],["Warning","1681","UNSIGNED for decimal and floating point data types is deprecated and support for it will be removed in a future release."],["Warning","1681","The ZEROFILL attribute is deprecated and will be removed in a future release. Use the LPAD function to zero-pad numbers, or store the formatted numbers in a CHAR column."],["Warning","1681","Integer display width is deprecated and will be removed in a future release."]]],
  ["CREATE TABLE p (id INT PRIMARY KEY)", [0,0,"",0]],
  ["CREATE TABLE c (pid INT, CONSTRAINT fk FOREIGN KEY (pid) REFERENCES p (id))", [0,0,"",0]],
  ["INSERT INTO p VALUES (1)", [1,0,"",0]],
  ["INSERT INTO c VALUES (1)", [1,0,"",0]],
  ["INSERT IGNORE INTO c VALUES (2)", [0,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1452","Cannot add or update a child row: a foreign key constraint fails (`app`.`c`, CONSTRAINT `fk` FOREIGN KEY (`pid`) REFERENCES `p` (`id`))"]]],
  ["DELETE IGNORE FROM p", [0,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1451","Cannot delete or update a parent row: a foreign key constraint fails (`app`.`c`, CONSTRAINT `fk` FOREIGN KEY (`pid`) REFERENCES `p` (`id`))"]]],
  ["INSERT IGNORE INTO p VALUES (1)", [0,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1062","Duplicate entry '1' for key 'p.PRIMARY'"]]],
  ["CREATE TABLE ck (a INT CHECK (a > 0))", [0,0,"",0]],
  ["INSERT IGNORE INTO ck VALUES (-1)", [0,0,"",1]],
  ["SHOW WARNINGS", [["Warning","3819","Check constraint 'ck_chk_1' is violated."]]],
  ["SELECT 1", [["1"]]],
  ["SHOW WARNINGS", []],
  ["SET sql_mode = ''", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["CREATE TABLE nn (i INT, d DATE, dt DATETIME, t TIME, y YEAR, dec1 DECIMAL(3,1), b BLOB, tx TINYTEXT, e ENUM('a'), s SET('a'), j JSON, bi BIT(2), c CHAR(2), vb VARBINARY(2))", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["INSERT INTO nn (i) VALUES ('abc')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1366","Incorrect integer value: 'abc' for column 'i' at row 1"]]],
  ["INSERT INTO nn (i) VALUES ('12x')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'i' at row 1"]]],
  ["INSERT INTO nn (d) VALUES ('2020-13-01')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'd' at row 1"]]],
  ["INSERT INTO nn (d) VALUES ('junk')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'd' at row 1"]]],
  ["INSERT INTO nn (dt) VALUES ('2020-02-30 10:00:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'dt' at row 1"]]],
  ["INSERT INTO nn (t) VALUES ('99:99:99')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 't' at row 1"]]],
  ["INSERT INTO nn (y) VALUES (1800)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'y' at row 1"]]],
  ["INSERT INTO nn (dec1) VALUES ('abc')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1366","Incorrect decimal value: 'abc' for column 'dec1' at row 1"]]],
  ["INSERT INTO nn (dec1) VALUES (1000)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'dec1' at row 1"]]],
  ["INSERT INTO nn (tx) VALUES (REPEAT('x', 300))", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'tx' at row 1"]]],
  ["INSERT INTO nn (e) VALUES ('b')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'e' at row 1"]]],
  ["INSERT INTO nn (s) VALUES ('a,b')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 's' at row 1"]]],
  ["INSERT INTO nn (bi) VALUES (9)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'bi' at row 1"]]],
  ["INSERT INTO nn (c) VALUES ('abc')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'c' at row 1"]]],
  ["INSERT INTO nn (vb) VALUES ('abc')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'vb' at row 1"]]],
  ["INSERT INTO nn (d) VALUES (20201301)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'd' at row 1"]]],
  ["SET sql_mode = DEFAULT", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["INSERT IGNORE INTO nn (d) VALUES ('junk')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'd' at row 1"]]],
  ["INSERT IGNORE INTO nn (c) VALUES ('abc')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'c' at row 1"]]],
  ["INSERT IGNORE INTO nn (i) VALUES ('abc')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1366","Incorrect integer value: 'abc' for column 'i' at row 1"]]],
  ["INSERT IGNORE INTO nn (e) VALUES ('b')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'e' at row 1"]]],
  ["INSERT IGNORE INTO nn (d) VALUES ('2020-13-01')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'd' at row 1"]]],
  ["DROP TABLE nn", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["SET sql_mode = ''", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["CREATE TABLE nn (d DATE, dt DATETIME, t TIME, ts TIMESTAMP)", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["INSERT INTO nn (dt) VALUES ('2020-13-01 10:00:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'dt' at row 1"]]],
  ["INSERT INTO nn (dt) VALUES ('2020-02-30')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'dt' at row 1"]]],
  ["INSERT INTO nn (dt) VALUES ('junk')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'dt' at row 1"]]],
  ["INSERT INTO nn (d) VALUES ('2020-02-30')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'd' at row 1"]]],
  ["INSERT INTO nn (d) VALUES ('2020-02-30 10:00:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'd' at row 1"]]],
  ["INSERT INTO nn (t) VALUES ('junk')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 't' at row 1"]]],
  ["INSERT INTO nn (t) VALUES ('10:99:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 't' at row 1"]]],
  ["INSERT INTO nn (t) VALUES ('900:00:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 't' at row 1"]]],
  ["INSERT INTO nn (ts) VALUES ('1960-01-01')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'ts' at row 1"]]],
  ["INSERT INTO nn (ts) VALUES ('2020-02-30')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'ts' at row 1"]]],
  ["INSERT INTO nn (dt) VALUES (20200230101010)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'dt' at row 1"]]],
  ["INSERT INTO nn (d) VALUES (20200230)", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'd' at row 1"]]],
  ["INSERT INTO nn (dt) VALUES ('2020-02-30 25:00:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'dt' at row 1"]]],
  ["INSERT INTO nn (dt) VALUES ('2020-01-01 25:00:00')", [1,0,"",1]],
  ["SHOW WARNINGS", [["Warning","1265","Data truncated for column 'dt' at row 1"]]],
  ["SET sql_mode = DEFAULT", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["INSERT INTO nn (dt) VALUES ('2020-02-30 10:00:00')", [1292,"Incorrect datetime value: '2020-02-30 10:00:00' for column 'dt' at row 1"]],
  ["SHOW WARNINGS", [["Error","1292","Incorrect datetime value: '2020-02-30 10:00:00' for column 'dt' at row 1"]]],
  ["INSERT INTO nn (t) VALUES ('99:99:99')", [1292,"Incorrect time value: '99:99:99' for column 't' at row 1"]],
  ["SHOW WARNINGS", [["Error","1292","Incorrect time value: '99:99:99' for column 't' at row 1"]]],
  ["INSERT INTO nn (d) VALUES ('2020-13-01')", [1292,"Incorrect date value: '2020-13-01' for column 'd' at row 1"]],
  ["SHOW WARNINGS", [["Error","1292","Incorrect date value: '2020-13-01' for column 'd' at row 1"]]],
  ["INSERT INTO nn (ts) VALUES ('1960-01-01')", [1292,"Incorrect datetime value: '1960-01-01' for column 'ts' at row 1"]],
  ["SHOW WARNINGS", [["Error","1292","Incorrect datetime value: '1960-01-01' for column 'ts' at row 1"]]],
  ["DROP TABLE nn", [0,0,"",0]],
  ["SHOW WARNINGS", []],
  ["CREATE TABLE e3 (id INT PRIMARY KEY, s VARCHAR(5), n INT, t TEXT)", [0,0,"",0]],
  ["INSERT INTO e3 VALUES (1, 'abc', 0, 'x'), (2, '2y', 1, '3z'), (3, '3', 2, '4')", [3,0,"Records: 3  Duplicates: 0  Warnings: 0",0]],
  ["SELECT 1/0, 1 DIV 0, 1 % 0, MOD(1, 0)", [[null,null,null,null]]],
  ["SHOW WARNINGS", [["Warning","1365","Division by 0"],["Warning","1365","Division by 0"],["Warning","1365","Division by 0"],["Warning","1365","Division by 0"]]],
  ["SELECT 'abc' + 1, '12x' + 1, ' 12' + 1, '1e2' + 0, '' + 0", [["1","13","13","100","0"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: '12x'"]]],
  ["SELECT 'abc' = 0, 'abc' < 1, 1 = 'x'", [["1","1","0"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'x'"]]],
  ["SELECT CAST('x' AS SIGNED), CAST('1.5x' AS DECIMAL(5,2)), CAST('abc' AS DOUBLE)", [["0","1.50","0"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect INTEGER value: 'x'"],["Warning","1292","Truncated incorrect DECIMAL value: '1.5x'"],["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"]]],
  ["SELECT 'abc' * 2, -'abc', ABS('x'), ROUND('x')", [["0","0","0","0"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'x'"],["Warning","1292","Truncated incorrect DOUBLE value: 'x'"]]],
  ["SELECT CONCAT(1/0)", [[null]]],
  ["SHOW WARNINGS", [["Warning","1365","Division by 0"]]],
  ["SELECT 1 FROM DUAL WHERE 'a' = 0", [["1"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'a'"]]],
  ["SELECT 'a' IN (0, 1)", [["1"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'a'"]]],
  ["SELECT SUM('x'), AVG('1y')", [["0","1"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'x'"],["Warning","1292","Truncated incorrect DOUBLE value: '1y'"]]],
  ["SELECT CAST('abc' AS CHAR(2)), CAST('abc' AS BINARY(2))", [["ab","ab"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect CHAR(2) value: 'abc'"],["Warning","1292","Truncated incorrect BINARY(2) value: 'abc'"]]],
  ["SELECT CAST(12345 AS DECIMAL(3,1)), CAST(-12345 AS DECIMAL(3,1)), CAST(99.95 AS DECIMAL(3,1)), cast(12345 as decimal(3, 1))", [["99.9","-99.9","99.9","99.9"]]],
  ["SHOW WARNINGS", [["Warning","1264","Out of range value for column 'CAST(12345 AS DECIMAL(3,1))' at row 1"],["Warning","1264","Out of range value for column 'CAST(-12345 AS DECIMAL(3,1))' at row 1"],["Warning","1264","Out of range value for column 'CAST(99.95 AS DECIMAL(3,1))' at row 1"],["Warning","1264","Out of range value for column 'cast(12345 as decimal(3, 1))' at row 1"]]],
  ["SELECT LEFT('abcdef', '2.7'), LEFT('abcdef', '2e1'), SUBSTRING('abcdef', '2.9'), REPEAT('a', '3.9'), '1.5' | 0, ~'2x'", [["ab","ab","bcdef","aaa","1","18446744073709551613"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect INTEGER value: '2.7'"],["Warning","1292","Truncated incorrect INTEGER value: '2e1'"],["Warning","1292","Truncated incorrect INTEGER value: '2.9'"],["Warning","1292","Truncated incorrect INTEGER value: '3.9'"],["Warning","1292","Truncated incorrect INTEGER value: '2.7'"],["Warning","1292","Truncated incorrect INTEGER value: '2e1'"],["Warning","1292","Truncated incorrect INTEGER value: '2.9'"],["Warning","1292","Truncated incorrect INTEGER value: '3.9'"],["Warning","1292","Truncated incorrect INTEGER value: '1.5'"],["Warning","1292","Truncated incorrect INTEGER value: '2x'"]]],
  ["SELECT CAST('12345678901234567890' AS SIGNED), CAST('-99999999999999999999' AS SIGNED), CAST(' -3x' AS SIGNED), CAST('+4' AS UNSIGNED), CAST('-1' AS UNSIGNED), CAST('' AS DECIMAL)", [["-6101065172474983726","-9223372036854775808","-3","4","18446744073709551615","0"]]],
  ["SHOW WARNINGS", [["Warning","1105","Cast to signed converted positive out-of-range integer to its negative complement"],["Warning","1292","Truncated incorrect INTEGER value: '-99999999999999999999'"],["Warning","1292","Truncated incorrect INTEGER value: ' -3x'"],["Warning","1105","Cast to unsigned converted negative integer to its positive complement"],["Warning","1292","Truncated incorrect DECIMAL value: ''"]]],
  ["SELECT 'abc' + 1 FROM e3", [["1"],["1"],["1"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"]]],
  ["SELECT id / n, id DIV n, MOD(id, n) FROM e3 ORDER BY id", [[null,null,null],["2.0000","2","0"],["1.5000","1","1"]]],
  ["SHOW WARNINGS", [["Warning","1365","Division by 0"],["Warning","1365","Division by 0"],["Warning","1365","Division by 0"]]],
  ["SELECT id FROM e3 WHERE id = 'abc'", []],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"]]],
  ["SELECT id FROM e3 WHERE id IN ('1x', 2)", [["1"],["2"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: '1x'"],["Warning","1292","Truncated incorrect DOUBLE value: '1x'"],["Warning","1292","Truncated incorrect DOUBLE value: '1x'"]]],
  ["SELECT LEFT('abc', s) FROM e3 ORDER BY id", [[""],["ab"],["abc"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect INTEGER value: 'abc'"],["Warning","1292","Truncated incorrect INTEGER value: '2y'"]]],
  ["SELECT t + 0, t * 1 FROM e3 ORDER BY id", [["0","0"],["3","3"],["4","4"]]],
  ["SHOW WARNINGS", []],
  ["SELECT FLOOR(s), SIGN(s) FROM e3 WHERE id <> 2 ORDER BY id", [["0","0"],["3","1"]]],
  ["SHOW WARNINGS", [["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"],["Warning","1292","Truncated incorrect DOUBLE value: 'abc'"]]],
  ["SELECT LPAD('a', 100000000, 'b') IS NULL, REPEAT('ab', 40000000) IS NULL, SPACE(70000000) IS NULL", [["1","1","1"]]],
  ["SHOW WARNINGS", [["Warning","1301","Result of lpad() was larger than max_allowed_packet (67108864) - truncated"],["Warning","1301","Result of repeat() was larger than max_allowed_packet (67108864) - truncated"],["Warning","1301","Result of space() was larger than max_allowed_packet (67108864) - truncated"]]],
  ["CREATE TABLE js (id INT, j JSON)", [0,0,"",0]],
  ["INSERT INTO js VALUES (1, '[1]'), (2, '{\"a\":1}'), (3, '1')", [3,0,"Records: 3  Duplicates: 0  Warnings: 0",0]],
  ["SELECT id FROM js ORDER BY j", [["3"],["2"],["1"]]],
  ["SHOW WARNINGS", [["Warning","1235","This version of MySQL doesn't yet support 'sorting of non-scalar JSON values'"]]],
  ["SELECT id, ROW_NUMBER() OVER (ORDER BY j) FROM js", [["3","1"],["2","2"],["1","3"]]],
  ["SHOW WARNINGS", [["Warning","1235","This version of MySQL doesn't yet support 'sorting of non-scalar JSON values'"]]],
  ["SELECT MAX(j) FROM js", [["1"]]],
  ["SHOW WARNINGS", []],
  ["SELECT @@warning_count", [["0"]]],
  ["SHOW COUNT(*) WARNINGS", [["0"]]],
  ["DROP TABLE e3, js", [0,0,"",0]],
]

test('SHOW WARNINGS lists every condition of each statement of the script as 8.4.11 did', async () => {
  const db = await MySQL.open(':memory:')
  const conn = await mysql.createConnection({ stream: db.createStream(), user: 'root', password: '', supportBigNumbers: true, bigNumberStrings: true, dateStrings: true })
  try {
    await conn.query('CREATE DATABASE app')
    await conn.query('USE app')
    for (const [sql, expected] of SCRIPT) {
      let actual: Outcome
      try {
        const [r] = await conn.query({ sql, rowsAsArray: true })
        if (Array.isArray(r)) actual = (r as unknown[][]).map((row) => row.map((v) => (v === null ? null : String(v))))
        else {
          const h = r as mysql.ResultSetHeader
          actual = [h.affectedRows, Number(h.insertId), h.info, h.warningStatus]
        }
      } catch (e) {
        const err = e as { errno: number; message: string }
        actual = [err.errno, err.message.replace(/#sql-[0-9a-f]+_[0-9a-f]+/g, '#sql-…')]
      }
      assert.deepEqual(actual, expected, sql)
    }
  } finally {
    await conn.end()
    await db.end()
  }
})
