// GENERATED by tools/capture-type-merge.mjs — do not edit (M5.2, D-39).
//
// The field type two values merge to where MySQL needs one type for several:
// CASE, IF, IFNULL, COALESCE. Asked of MySQL 8.4.11: for every pair of a
// table's column types and NULL, the type `COALESCE(a, b)`, `IF(c, a, b)` and
// `CASE WHEN c THEN a ELSE b END` report, which the capture checked agree.
// VARCHAR stands for both VARCHAR and VAR_STRING, which is how a VARCHAR goes
// on the wire. Row a, column b, is a letter: the merged type's place in
// MERGE_TYPES, `a` for the first.

export type MergeType = 'TINY' | 'SHORT' | 'INT24' | 'LONG' | 'LONGLONG' | 'NEWDECIMAL' | 'FLOAT' | 'DOUBLE' | 'BIT' | 'YEAR' | 'DATE' | 'TIME' | 'DATETIME' | 'TIMESTAMP' | 'STRING' | 'VARCHAR' | 'TINY_BLOB' | 'BLOB' | 'MEDIUM_BLOB' | 'LONG_BLOB' | 'ENUM' | 'SET' | 'JSON' | 'NULL'

/** The types in the order the table indexes them. */
export const MERGE_TYPES: readonly MergeType[] = ['TINY', 'SHORT', 'INT24', 'LONG', 'LONGLONG', 'NEWDECIMAL', 'FLOAT', 'DOUBLE', 'BIT', 'YEAR', 'DATE', 'TIME', 'DATETIME', 'TIMESTAMP', 'STRING', 'VARCHAR', 'TINY_BLOB', 'BLOB', 'MEDIUM_BLOB', 'LONG_BLOB', 'ENUM', 'SET', 'JSON', 'NULL']

const TABLE: readonly string[] = [
  'abcdefghfappppoprrrrppta', // TINY
  'bbcdefghfbppppoprrrrpptb', // SHORT
  'cccdefghfcppppoprrrrpptc', // INT24
  'ddddefhhfdppppoprrrrpptd', // LONG
  'eeeeefhhfeppppoprrrrppte', // LONGLONG
  'ffffffhhffppppoprrrrpptf', // NEWDECIMAL
  'ggghghghhgppppoprrrrpptg', // FLOAT
  'hhhhhhhhhhppppoprrrrppth', // DOUBLE
  'ffffffhhieppppoprrrrppti', // BIT
  'abcdefghejppppoprrrrpptj', // YEAR
  'ppppppppppkmmmoprrrrpptk', // DATE
  'ppppppppppmlmmoprrrrpptl', // TIME
  'ppppppppppmmmmoprrrrpptm', // DATETIME
  'ppppppppppmmmnoprrrrpptn', // TIMESTAMP
  'oooooooooooooooprrrrooto', // STRING
  'pppppppppppppppprrrrpptp', // VARCHAR
  'rrrrrrrrrrrrrrrrrrrrrrtr', // TINY_BLOB
  'rrrrrrrrrrrrrrrrrrrrrrtr', // BLOB
  'rrrrrrrrrrrrrrrrrrrrrrtr', // MEDIUM_BLOB
  'rrrrrrrrrrrrrrrrrrrrrrtr', // LONG_BLOB
  'ppppppppppppppoprrrrpptu', // ENUM
  'ppppppppppppppoprrrrpptv', // SET
  'ttttttttttttttttttttttww', // JSON
  'abcdefghijklmnoprrrruvwx', // NULL
]

/** The field type `a` and `b` merge to. */
export function mergeTypes(a: MergeType, b: MergeType): MergeType {
  return MERGE_TYPES[(TABLE[MERGE_TYPES.indexOf(a)] as string).charCodeAt(MERGE_TYPES.indexOf(b)) - 97] as MergeType
}
